{"trial_id": "2", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "units", "default": 8, "conditions": [], "values": [8, 16, 32], "ordered": true}}], "values": {"units": 16}}, "metrics": {"metrics": {"loss": {"direction": "min", "observations": [{"value": [0.06339475512504578], "step": 1}]}, "val_loss": {"direction": "min", "observations": [{"value": [0.0549330860376358], "step": 1}]}}}, "score": 0.0549330860376358, "best_step": 1, "status": "COMPLETED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\dinhc\\anaconda3\\envs\\true1\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py\", line 102, in convert_to_eager_tensor\n    return ops.EagerTensor(value, ctx.device_name, dtype)\nValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).\n"}